repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: viralmixedassembly
  description: 'Pipeline for dual assembly of viral sequences from illumina short
    reads using mapping-based and de novo strategies and merging the resultant consensus
    sequences into a mixed viral consensus sequence. '
  author: "Germ\xE1n Vallejo Palma"
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
