contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #viralmixedassembly channel"
    url: https://nfcore.slack.com/channels/viralmixedassembly
    about: Discussion about the nf-core/viralmixedassembly pipeline
